#! /bin/sh

### AUTOSTART ###
sxhkd &
nitrogen --restore &
polybar meinbar &
picom &
emacs --daemon &
setxkbmap -layout us,rs -option "grp:alt_shift_toggle,grp_led:scroll" &
pgrep -x sxhkd > /dev/null || sxhkd &
### END ###

### WORKSPACES ###
bspc monitor -d I II III IV V VI VII VIII IX X
### END ###

### BORDER ###
bspc config border_width         2
bspc config window_gap          12
## BORDER COLOUR ##

# Gruvbox dark
#bspc config focused_border_color    '#83a598'
#bspc config active_border_color  '#1d2021'
#bspc config normal_border_color '#1d2021'
# End #

# Onedark
#bspc config focused_border_color    '#528bff'
# bspc config active_border_color  '#282c34'
# bspc config normal_border_color '#282c34'
### END ###

# Modus Vivendi #
#bspc config focused_border_color '#ff8059'
 bspc config focused_border_color '#b6a0ff'
bspc config active_border_color  '#000000'
bspc config normal_border_color '#000000'
## END ##

# Horizon
#bspc config focused_border_color '#E95379'

### LAYOUTS ###
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
### END ###

### WINDOW RULES ###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
### END ###
